QLNS/Models/Organization.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Organization
    {
        public long OrganizationId { get; set; }
        public string OrganizationCode { get; set; }
        public string OrganizationName { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> EffectiveStartDate { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> EffectiveEndDate { get; set; }
        public string Address { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}

QLNS/Controllers/OrganizationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using QLNS.Models;

namespace QLNS.Controllers
{
    public class OrganizationsController : Controller
    {
        private QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();

        // GET: Organizations
        public ActionResult Index(int PageIndex = 1, string TextSearch = "")
        {
            IQueryable<Organization> data = db.Organizations;
            ViewBag.TextSearch = "";
            // nếu có dữ liệu truyền vào TextSearch, tìm kiếm theo UserName 
            if (!string.IsNullOrEmpty(TextSearch))
            {
                ViewBag.TextSearch = TextSearch;
                data = data.Where(n => n.OrganizationName.Contains(TextSearch) || n.OrganizationCode.Contains(TextSearch));
            }
            ViewBag.status = Common.Common.GetStatuses;
            // phân trang
            var list = data.OrderByDescending(n => n.OrganizationId).ToPagedList(PageIndex, 10);
            return View(list);
        }

        // GET: Organizations/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organization organization = db.Organizations.Find(id);
            var statuses = Common.Common.GetStatuses;
            ViewBag.status = Common.Common.GetStatuses.FirstOrDefault(n => n.StatusId == organization.IsActive);
            if (organization == null)
            {
                return HttpNotFound();
            }
            return View(organization);
        }

        // GET: Organizations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Organizations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrganizationId,OrganizationCode,OrganizationName,EffectiveStartDate,EffectiveEndDate,Address,IsActive,CreatedAt,UpdatedAt")] Organization organization)
        {
            if (ModelState.IsValid)
            {
                organization.CreatedAt = DateTime.Now;
                organization.UpdatedAt = DateTime.Now;
                organization.IsActive = 1;
                db.Organizations.Add(organization);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(organization);
        }

        // GET: Organizations/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organization organization = db.Organizations.Find(id);
            var statuses = Common.Common.GetStatuses;
            var status = Common.Common.GetStatuses.FirstOrDefault(n => n.StatusId == organization.IsActive);
            ViewBag.statuses = new SelectList(statuses, "StatusId", "StatusName");
            
            if (organization == null)
            {
                return HttpNotFound();
            }
            return View(organization);
        }

        // POST: Organizations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrganizationId,OrganizationCode,OrganizationName,EffectiveStartDate,EffectiveEndDate,Address,IsActive,CreatedAt,UpdatedAt")] Organization organization)
        {
            if (ModelState.IsValid)
            {
                organization.UpdatedAt = DateTime.Now;
                db.Entry(organization).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(organization);
        }

        // GET: Organizations/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organization organization = db.Organizations.Find(id);
            var statuses = Common.Common.GetStatuses;
            ViewBag.status = Common.Common.GetStatuses.FirstOrDefault(n => n.StatusId == organization.IsActive);
            if (organization == null)
            {
                return HttpNotFound();
            }
            return View(organization);
        }

        // POST: Organizations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Organization organization = db.Organizations.Find(id);
            db.Organizations.Remove(organization);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLNS/Views/Organizations/Create.cshtml
@model QLNS.Models.Organization

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/datetimepicker/css/bootstrap-datepicker3.min.css" rel="stylesheet" />
<script src="~/Content/datetimepicker/js/bootstrap-datepicker.min.js"></script>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.OrganizationCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrganizationCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrganizationCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrganizationName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrganizationName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrganizationName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EffectiveStartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.EffectiveStartDate, new { @class = "form-control begin-date" })
                @Html.ValidationMessageFor(model => model.EffectiveStartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EffectiveEndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.EffectiveEndDate, new { @class = "form-control end-date" })
                @Html.ValidationMessageFor(model => model.EffectiveEndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở lại", "Index", null, new { @class = "btn btn-success" })
</div>
<script>
    $(() => {
        $('.begin-date').datepicker();
        $('.end-date').datepicker();
    })
</script>

QLNS/Views/Organizations/Delete.cshtml
@model QLNS.Models.Organization

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var status = ViewBag.status as QLNS.Common.Status;
}


<h3>Bạn chắc chắn muốn xóa ?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrganizationCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrganizationCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrganizationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrganizationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EffectiveStartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EffectiveStartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EffectiveEndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EffectiveEndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @(status.StatusName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-danger" /> |
            @Html.ActionLink("Trở lại", "Index", null, new {@class="btn btn-success" })
        </div>
    }
</div>

QLNS/Views/Organizations/Details.cshtml
@model QLNS.Models.Organization

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var status = ViewBag.status as QLNS.Common.Status;
}

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrganizationCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrganizationCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrganizationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrganizationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EffectiveStartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EffectiveStartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EffectiveEndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EffectiveEndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @(status.StatusName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.OrganizationId }, new {@class="btn btn-warning" }) |
    @Html.ActionLink("Trở lại", "Index", null, new {@class="btn btn-success" })
</p>

QLNS/Views/Organizations/Edit.cshtml
@model QLNS.Models.Organization

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/datetimepicker/css/bootstrap-datepicker3.min.css" rel="stylesheet" />
<script src="~/Content/datetimepicker/js/bootstrap-datepicker.min.js"></script>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.OrganizationId)

    <div class="form-group">
        @Html.LabelFor(model => model.OrganizationCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OrganizationCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OrganizationCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OrganizationName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OrganizationName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OrganizationName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EffectiveStartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.EffectiveStartDate, new { @class = "form-control begin-date" })
            @Html.ValidationMessageFor(model => model.EffectiveStartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EffectiveEndDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.EffectiveEndDate, new { @class = "form-control end-date" })
            @Html.ValidationMessageFor(model => model.EffectiveEndDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.IsActive, (IEnumerable<SelectListItem>)ViewBag.statuses, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Trở lại", "Index", null, new { @class = "btn btn-success" })
</div>
<script>
    $(() => {
        $('.begin-date').datepicker();
        $('.end-date').datepicker();
    })
</script>

QLNS/Views/Organizations/Index.cshtml
@model PagedList.IPagedList<QLNS.Models.Organization>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="row">
        <p class="col-md-6">
            @Html.ActionLink("Thêm", "Create", null, new { @class = "btn btn-primary" })
        </p>
        <div class="col-md-6">
            <form action="/Organizations/Index" method="get" class="d-flex float-right">
                <input type="text" name="TextSearch" value="@ViewBag.TextSearch" class="form-control w-75" />
                <input type="submit" class="btn btn-info" value="Tìm Kiếm" />
            </form>
        </div>
    </div>
</div>
<table class="table table-bordered">
    <tr>
        <th>
            @Html.Label("OrganizationCode")
        </th>
        <th>
            @Html.Label("OrganizationName")
        </th>
        <th>
            @Html.Label("EffectiveStartDate")
        </th>
        <th>
            @Html.Label("EffectiveEndDate")
        </th>
        <th>
            @Html.Label("Address")
        </th>
        <th>
            @Html.Label("IsActive")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OrganizationCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrganizationName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EffectiveStartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EffectiveEndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @{ var status = ((List<QLNS.Common.Status>)ViewBag.status).FirstOrDefault(n => n.StatusId == item.IsActive); }
                @Html.DisplayFor(modelItem => status.StatusName)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.OrganizationId }) |
                @Html.ActionLink("Xem", "Details", new { id = item.OrganizationId }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.OrganizationId })
            </td>
        </tr>
    }

</table>
@Html.PagedListPager(Model,
PageIndex => Url.Action("Index", "Organizations", new { PageIndex }),
    new PagedListRenderOptions
    {
        LiElementClasses = new string[] { "page-item" },
        UlElementClasses = new List<string> { "pagination", "pagination sm" },
        ContainerDivClasses = new List<string> { "nav text-xs-center" },
        FunctionToTransformEachPageLink = (liTag, aTag) => { aTag.Attributes.Add("class", "page-link"); liTag.InnerHtml = aTag.ToString(); return liTag; },
        LinkToPreviousPageFormat = "Previous",
        LinkToNextPageFormat = "Next",
        DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
        DisplayLinkToNextPage = PagedListDisplayMode.Always
    }
)